print('hi i am body mass bot')
weight = float(input('how much do you weigh in kilograms'))
height = float(input('how tall are you in meters'))
BMI = weight / (height * height)
print(f'your body mass index is {BMI}')
